name: 'blog_content'
version: '1.0'
config-version: 2
profile: 'blog'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

models:
  blog:
    # Staging モデル用の設定
    staging:
      +materialized: view  # ステージングはビューとして作成
      +schema: staging    # staging スキーマに作成
      
    # Intermediate モデル用の設定
    intermediate:
      +materialized: table
      +schema: intermediate
    
    # Marts モデル用の設定
    marts:
      +materialized: table  # マートはテーブルとして作成
      +schema: marts       # marts スキーマに作成
      
      blog:
        +materialized: table  # マートはテーブルとして作成
        +schema: marts

# カスタム変数の設定（必要な場合）
vars:
  schema_prefix: 'prod'
