pokemon_analysis:
  target: dev
  outputs:
    dev:
      type: duckdb
      schema: main 
      path: './{{ env_var("DUCKDB_DATABASE", "data/staging/data.duckdb") }}'
      extensions: 
        - httpfs

    prod:
      type: duckdb
      schema: agg
      #path: 'md:pokemon'
      path:  "md:pokemon?motherduck_token={{env_var('MOTHERDUCK_TOKEN')}}"
      threads: 16
      extensions: 
        - httpfs