version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      #- host-node-modules:/app/node_modules
      #- host-evidence:/app/.evidence
    env_file:
      - .env
    command: sh -c "npm run sources && npm run dev"
